# Generated by Django 5.1.6 on 2025-11-17 01:00
# Empty migration - stub to satisfy migration history

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventfeedback_eventwaitlist_and_more'),
    ]

    operations = [
        # Empty - індекси вже оброблені в попередніх міграціях
    ]

