# Generated by Django 5.1.3 on 2025-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_registration_data_to_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='event_banners/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, upload_to='event_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=500, upload_to='ticket_qr/'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, upload_to='speaker_photos/'),
        ),
    ]

