# Generated by Django on 2025-11-20
# Add is_online_event field to Event model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_make_event_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_online_event',
            field=models.BooleanField(
                default=False,
                help_text='Поставте галочку якщо подія проводиться онлайн',
                verbose_name='Онлайн подія'
            ),
        ),
    ]

