# Generated by Django 5.1.6 on 2025-09-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, help_text='Applied coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount in currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='tips_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tips amount for content authors', max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='content_type_display',
            field=models.CharField(blank=True, help_text='Display type like "VIDEO • 95 ХВ"', max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Tags, badges, etc. {"tags": ["тренер"], "badges": ["топ-продажів"]}'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Product thumbnail URL'),
        ),
    ]
