# Generated by Django 5.1.6 on 2025-10-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_add_lifetime_spent_points'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pointtransaction',
            new_name='point_trans_account_6fd5a0_idx',
            old_name='point_trans_account_idx',
        ),
        migrations.RenameIndex(
            model_name='pointtransaction',
            new_name='point_trans_referen_0a803d_idx',
            old_name='point_trans_reference_idx',
        ),
    ]
