# Generated by Django 5.1.6 on 2025-11-17 01:00
# Empty migration - stub to satisfy migration history

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_rename_point_trans_account_idx_point_trans_account_6fd5a0_idx_and_more'),
    ]

    operations = [
        # Empty - індекси вже перейменовані через 0003
    ]

