# Generated by Django 5.1.6 on 2025-09-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='s3_video_key',
            field=models.CharField(blank=True, help_text='Ключ відео в S3 bucket', max_length=500),
        ),
        migrations.AddField(
            model_name='material',
            name='secure_video_enabled',
            field=models.BooleanField(default=False, help_text='Використовувати захищену доставку відео'),
        ),
        migrations.AddField(
            model_name='material',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='video_access_token',
            field=models.CharField(blank=True, help_text='Поточний токен доступу', max_length=100),
        ),
    ]
