# Generated by Django 5.1.6 on 2025-10-26 10:57

from django.db import migrations, connection


def rename_indexes_if_exist(apps, schema_editor):
    """Перейменовує індекси тільки якщо вони існують"""
    db_alias = schema_editor.connection.alias
    
    try:
        with connection.cursor() as cursor:
            # Перевіряємо які індекси існують для monthly_quotes
            if connection.vendor == 'postgresql':
                # Перевіряємо чи існує таблиця monthly_quotes
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM information_schema.tables 
                        WHERE table_name='monthly_quotes' AND table_schema='public'
                    )
                """)
                if not cursor.fetchone()[0]:
                    print("Table monthly_quotes does not exist, skipping index renames")
                    return
                    
                cursor.execute("""
                    SELECT indexname 
                    FROM pg_indexes 
                    WHERE tablename='monthly_quotes' AND schemaname='public'
                """)
                monthly_quotes_indexes = {row[0] for row in cursor.fetchall()}
                
                # Перевіряємо чи існує таблиця tags
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM information_schema.tables 
                        WHERE table_name='tags' AND table_schema='public'
                    )
                """)
                if not cursor.fetchone()[0]:
                    print("Table tags does not exist, skipping index renames")
                    return
                
                cursor.execute("""
                    SELECT indexname 
                    FROM pg_indexes 
                    WHERE tablename='tags' AND schemaname='public'
                """)
                tags_indexes = {row[0] for row in cursor.fetchall()}
            else:
                # SQLite
                try:
                    cursor.execute("PRAGMA index_list(monthly_quotes)")
                    monthly_quotes_indexes = {row[1] for row in cursor.fetchall()}
                except Exception:
                    monthly_quotes_indexes = set()
                
                try:
                    cursor.execute("PRAGMA index_list(tags)")
                    tags_indexes = {row[1] for row in cursor.fetchall()}
                except Exception:
                    tags_indexes = set()
        
        # Перейменовуємо індекси monthly_quotes
        if 'monthly_quotes_month_active_idx' in monthly_quotes_indexes and 'monthly_quo_month_cc6c8a_idx' not in monthly_quotes_indexes:
            try:
                if connection.vendor == 'postgresql':
                    cursor.execute('ALTER INDEX monthly_quotes_month_active_idx RENAME TO monthly_quo_month_cc6c8a_idx')
                    print("Renamed index monthly_quotes_month_active_idx to monthly_quo_month_cc6c8a_idx")
            except Exception as e:
                print(f"Warning: Could not rename index monthly_quotes_month_active_idx: {e}")
        elif 'monthly_quo_month_cc6c8a_idx' in monthly_quotes_indexes:
            print("Index monthly_quo_month_cc6c8a_idx already exists, skipping rename")
        else:
            print("Index monthly_quotes_month_active_idx does not exist, skipping rename")
        
        # Перейменовуємо індекси tags
        if 'tags_type_order_idx' in tags_indexes and 'tags_tag_typ_cd4419_idx' not in tags_indexes:
            try:
                if connection.vendor == 'postgresql':
                    cursor.execute('ALTER INDEX tags_type_order_idx RENAME TO tags_tag_typ_cd4419_idx')
                    print("Renamed index tags_type_order_idx to tags_tag_typ_cd4419_idx")
            except Exception as e:
                print(f"Warning: Could not rename index tags_type_order_idx: {e}")
        elif 'tags_tag_typ_cd4419_idx' in tags_indexes:
            print("Index tags_tag_typ_cd4419_idx already exists, skipping rename")
        else:
            print("Index tags_type_order_idx does not exist, skipping rename")
    
    except Exception as e:
        # Якщо щось пішло не так, просто пропускаємо без помилки
        # Це безпечно для продакшену
        print(f"Warning: Could not rename indexes: {e}")
        print("Continuing migration without index renames...")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_add_course_logo'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_exist, migrations.RunPython.noop),
    ]
