# Generated by Django 5.1.6 on 2025-10-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_add_course_logo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlyquote',
            new_name='monthly_quo_month_cc6c8a_idx',
            old_name='monthly_quotes_month_active_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='tags_tag_typ_cd4419_idx',
            old_name='tags_type_order_idx',
        ),
    ]
