# Generated by Django 5.1.6 on 2025-11-16 17:49

import django.db.models.deletion
from django.db import migrations, models
from django.db import connection


def safe_remove_fields(apps, schema_editor):
    """Safely remove fields only if they exist"""
    Course = apps.get_model('content', 'Course')
    
    # Get existing field names from the model state
    existing_fields = [f.name for f in Course._meta.get_fields()]
    
    # Only remove fields that exist
    fields_to_remove = ['badge_type', 'content_type', 'difficulty', 'duration_minutes', 
                        'is_classic', 'training_specialization']
    
    with connection.cursor() as cursor:
        # Check which columns actually exist in the database
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='courses' AND table_schema='public'
            """)
        else:
            cursor.execute("PRAGMA table_info(courses)")
        
        existing_columns = {row[0] if connection.vendor == 'postgresql' else row[1] for row in cursor.fetchall()}
        
        # Remove each field if it exists
        for field_name in fields_to_remove:
            if field_name in existing_columns:
                try:
                    cursor.execute(f"ALTER TABLE courses DROP COLUMN {field_name}")
                except Exception as e:
                    print(f"Warning: Could not remove {field_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rename_monthly_quotes_month_active_idx_monthly_quo_month_cc6c8a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        
        # Run Python to safely remove fields if they exist
        migrations.RunPython(safe_remove_fields, migrations.RunPython.noop),
        
        migrations.AddField(
            model_name='category',
            name='is_subcategory_required',
            field=models.BooleanField(default=False, help_text='Для "Тренерство" - обов\'язково вибирати підкатегорію', verbose_name="Підкатегорія обов'язкова"),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок відображення в фільтрах', verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Залиште порожнім для головної категорії', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='content.category', verbose_name='Батьківська категорія'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(help_text='Оберіть категорію курсу. Для "Тренерство" обов\'язково вкажіть підкатегорію.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='content.category', verbose_name='Категорія'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'order'], name='categories_parent__60b507_idx'),
        ),
    ]
