# Generated by Django 5.1.6 on 2025-11-16 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rename_monthly_quotes_month_active_idx_monthly_quo_month_cc6c8a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameIndex(
            model_name='monthlyquote',
            new_name='monthly_quo_month_cc6c8a_idx',
            old_name='monthly_quotes_month_active_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='tags_tag_typ_cd4419_idx',
            old_name='tags_type_order_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='badge_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_classic',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='course',
            name='training_specialization',
        ),
        migrations.AddField(
            model_name='category',
            name='is_subcategory_required',
            field=models.BooleanField(default=False, help_text='Для "Тренерство" - обов\'язково вибирати підкатегорію', verbose_name="Підкатегорія обов'язкова"),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок відображення в фільтрах', verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Залиште порожнім для головної категорії', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='content.category', verbose_name='Батьківська категорія'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(help_text='Оберіть категорію курсу. Для "Тренерство" обов\'язково вкажіть підкатегорію.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='content.category', verbose_name='Категорія'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'order'], name='categories_parent__60b507_idx'),
        ),
    ]
