# Generated by Django 5.1.6 on 2025-11-20 14:05
# Migration to sync Django state with existing MonthlyQuote table

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_course_target_audience'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Add MonthlyQuote model to Django state
                migrations.CreateModel(
                    name='MonthlyQuote',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('expert_name', models.CharField(max_length=100, verbose_name='Імʼя експерта')),
                        ('expert_role', models.CharField(max_length=150, verbose_name='Посада/роль')),
                        ('expert_photo', models.ImageField(blank=True, max_length=100, upload_to='experts/monthly_quotes/', verbose_name='Фото експерта')),
                        ('quote_text', models.TextField(verbose_name='Текст цитати')),
                        ('month', models.DateField(help_text='Завжди 1-е число місяця (напр. 2025-10-01)', unique=True, verbose_name='Місяць')),
                        ('is_active', models.BooleanField(default=True, help_text='Тільки одна цитата може бути активною для поточного місяця', verbose_name='Активна')),
                        ('views_count', models.PositiveIntegerField(default=0)),
                        ('last_displayed_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Цитата місяця',
                        'verbose_name_plural': 'Цитати місяця',
                        'db_table': 'monthly_quotes',
                        'ordering': ['-month'],
                        'indexes': [models.Index(fields=['month', 'is_active'], name='monthly_quotes_month_active_idx')],
                    },
                ),
            ],
            # No database operations - table already exists
            database_operations=[],
        ),
    ]

