# Generated by Django 5.1.6 on 2025-11-16 17:49

from django.db import migrations


def create_new_categories(apps, schema_editor):
    """Створення нових категорій згідно нової структури"""
    Category = apps.get_model('content', 'Category')
    
    # Видалити старі категорії (якщо є)
    Category.objects.all().delete()
    
    # Головна категорія "Тренерство" з обов'язковими підкатегоріями
    trenerstvo = Category.objects.create(
        name='Тренерство',
        slug='trenerstvo',
        description='Навчальні матеріали для тренерів',
        order=1,
        is_subcategory_required=True,
        is_active=True
    )
    
    # Підкатегорії тренерства
    Category.objects.create(
        name='Тренер воротарів',
        slug='coach-gk',
        parent=trenerstvo,
        order=1,
        is_active=True
    )
    Category.objects.create(
        name='Дитячий тренер',
        slug='coach-youth',
        parent=trenerstvo,
        order=2,
        is_active=True
    )
    Category.objects.create(
        name='Тренер ЗФП',
        slug='coach-fitness',
        parent=trenerstvo,
        order=3,
        is_active=True
    )
    Category.objects.create(
        name='Тренер професійних команд',
        slug='coach-pro',
        parent=trenerstvo,
        order=4,
        is_active=True
    )
    
    # Інші головні категорії (без підкатегорій)
    Category.objects.create(
        name='Аналітика і скаутинг',
        slug='analytics',
        description='Матеріали з аналітики та скаутингу',
        order=2,
        is_active=True
    )
    Category.objects.create(
        name='Менеджмент',
        slug='management',
        description='Менеджмент у футболі',
        order=3,
        is_active=True
    )
    Category.objects.create(
        name='Спортивна психологія',
        slug='psychology',
        description='Психологія у спорті',
        order=4,
        is_active=True
    )
    Category.objects.create(
        name='Нутриціологія',
        slug='nutrition',
        description='Харчування спортсменів',
        order=5,
        is_active=True
    )
    Category.objects.create(
        name='Реабілітація',
        slug='rehabilitation',
        description='Реабілітація та відновлення',
        order=6,
        is_active=True
    )
    Category.objects.create(
        name='Футболіст',
        slug='player',
        description='Матеріали для гравців',
        order=7,
        is_active=True
    )
    Category.objects.create(
        name='Батько',
        slug='parent',
        description='Матеріали для батьків юних футболістів',
        order=8,
        is_active=True
    )


def reverse_categories(apps, schema_editor):
    """Видалення категорій при rollback"""
    Category = apps.get_model('content', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_redesign_filters'),
    ]

    operations = [
        migrations.RunPython(create_new_categories, reverse_categories),
    ]
