# Generated by Django 5.1.6 on 2025-11-16 17:49

from django.db import migrations


def create_new_categories(apps, schema_editor):
    """Створення нових категорій згідно нової структури"""
    Category = apps.get_model('content', 'Category')
    
    # НЕ видаляємо існуючі категорії! Створюємо тільки якщо їх немає
    # Це безпечно для продакшену де є курси прив'язані до категорій
    
    # Головна категорія "Тренерство" з обов'язковими підкатегоріями
    trenerstvo, created = Category.objects.get_or_create(
        slug='trenerstvo',
        defaults={
            'name': 'Тренерство',
            'description': 'Навчальні матеріали для тренерів',
            'order': 1,
            'is_subcategory_required': True,
            'is_active': True
        }
    )
    if not created:
        # Оновлюємо існуючу категорію
        trenerstvo.is_subcategory_required = True
        trenerstvo.order = 1
        trenerstvo.save()
    
    # Підкатегорії тренерства
    Category.objects.get_or_create(
        slug='coach-gk',
        defaults={
            'name': 'Тренер воротарів',
            'parent': trenerstvo,
            'order': 1,
            'is_active': True
        }
    )
    Category.objects.get_or_create(
        slug='coach-youth',
        defaults={
            'name': 'Дитячий тренер',
            'parent': trenerstvo,
            'order': 2,
            'is_active': True
        }
    )
    Category.objects.get_or_create(
        slug='coach-fitness',
        defaults={
            'name': 'Тренер ЗФП',
            'parent': trenerstvo,
            'order': 3,
            'is_active': True
        }
    )
    Category.objects.get_or_create(
        slug='coach-pro',
        defaults={
            'name': 'Тренер професійних команд',
            'parent': trenerstvo,
            'order': 4,
            'is_active': True
        }
    )
    
    # Інші головні категорії (без підкатегорій)
    Category.objects.get_or_create(
        slug='analytics',
        defaults={
            'name': 'Аналітика та скаутинг',
            'description': 'Матеріали з аналітики та скаутингу',
            'order': 2,
            'is_active': True
        }
    )
    Category.objects.get_or_create(
        slug='management',
        defaults={
            'name': 'Менеджмент',
            'description': 'Менеджмент у футболі',
            'order': 3,
            'is_active': True
        }
    )
    Category.objects.get_or_create(
        slug='psychology',
        defaults={
            'name': 'Спортивна психологія',
            'description': 'Психологія у спорті',
            'order': 4,
            'is_active': True
        }
    )
    Category.objects.get_or_create(
        slug='nutrition',
        defaults={
            'name': 'Нутриціологія',
            'description': 'Харчування спортсменів',
            'order': 5,
            'is_active': True
        }
    )
    Category.objects.get_or_create(
        slug='rehabilitation',
        defaults={
            'name': 'Реабілітація',
            'description': 'Реабілітація та відновлення',
            'order': 6,
            'is_active': True
        }
    )
    Category.objects.get_or_create(
        slug='player',
        defaults={
            'name': 'Футболіст',
            'description': 'Матеріали для гравців',
            'order': 7,
            'is_active': True
        }
    )
    Category.objects.get_or_create(
        slug='parent',
        defaults={
            'name': 'Батько',
            'description': 'Матеріали для батьків юних футболістів',
            'order': 8,
            'is_active': True
        }
    )


def reverse_categories(apps, schema_editor):
    """Видалення категорій при rollback"""
    Category = apps.get_model('content', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_redesign_filters'),
    ]

    operations = [
        migrations.RunPython(create_new_categories, reverse_categories),
    ]
