# Generated by Django 5.1.3 on 2025-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_course_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, help_text='Квадратне лого курсу для відображення на картці (рекомендовано 200x200px)', max_length=500, null=True, upload_to='course_logos/', verbose_name='Лого курсу'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_video',
            field=models.FileField(blank=True, max_length=500, upload_to='course_previews/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(max_length=500, upload_to='course_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, upload_to='materials/pdfs/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, upload_to='materials/videos/'),
        ),
        migrations.AlterField(
            model_name='monthlyquote',
            name='expert_photo',
            field=models.ImageField(blank=True, max_length=500, upload_to='experts/monthly_quotes/', verbose_name='Фото експерта'),
        ),
    ]

