# Generated by Django 5.1.6 on 2025-11-17 01:00
# Empty migration - stub to satisfy migration history

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_populate_new_categories'),
    ]

    operations = [
        # Empty - індекси вже перейменовані через 0010
    ]

