# Generated by Django 5.1.6 on 2025-11-16 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when object was last updated')),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=200)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], db_index=True, max_length=10)),
                ('changes', models.JSONField(default=dict, help_text='Field changes: {"field": {"old": "...", "new": "..."}}')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'core_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_audit__content_f7bd8a_idx'), models.Index(fields=['user', 'timestamp'], name='core_audit__user_id_607f52_idx'), models.Index(fields=['action', 'timestamp'], name='core_audit__action_b54425_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when object was last updated')),
                ('object_id', models.PositiveIntegerField()),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version number')),
                ('snapshot', models.JSONField(help_text='Complete serialized object state')),
                ('change_summary', models.TextField(blank=True, help_text='Optional summary of changes in this version')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Content Version',
                'verbose_name_plural': 'Content Versions',
                'db_table': 'cms_content_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-version_number'], name='cms_content_content_b6e656_idx'), models.Index(fields=['created_by', '-created_at'], name='cms_content_created_9c6334_idx')],
                'unique_together': {('content_type', 'object_id', 'version_number')},
            },
        ),
    ]
