# Generated by Django 5.1.6 on 2025-11-21 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when object was last updated')),
                ('slug', models.CharField(choices=[('privacy', 'Політика конфіденційності'), ('terms', 'Умови використання'), ('offer', 'Публічна оферта')], help_text='URL-ключ документа', max_length=50, unique=True, verbose_name='Тип документа')),
                ('title', models.CharField(help_text='Заголовок документа', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Повний текст документа (HTML дозволено)', verbose_name='Зміст')),
                ('version_date', models.DateField(default=django.utils.timezone.now, help_text='Дата поточної редакції документа', verbose_name='Дата редакції')),
                ('is_active', models.BooleanField(default=True, help_text='Показувати документ на сайті', verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Юридичний документ',
                'verbose_name_plural': '📋 Юридичні документи',
                'db_table': 'core_legal_pages',
                'ordering': ['slug'],
            },
        ),
    ]
