# Generated by Django 5.1.3 on 2025-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoringdirection',
            name='background_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='mentoring/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='mentoringdirection',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='mentoring/directions/'),
        ),
        migrations.AlterField(
            model_name='mentoringmentor',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, upload_to='mentoring/mentors/'),
        ),
        migrations.AlterField(
            model_name='mentoringprogram',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, upload_to='mentoring/programs/'),
        ),
    ]

