# Generated by Django 4.2 on 2025-11-19 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наприклад: C-Vision, PRO-Vision', max_length=100, verbose_name='Назва тарифу')),
                ('slug', models.SlugField(help_text='Автоматично генерується з назви', unique=True, verbose_name='Slug (URL)')),
                ('badge_text', models.CharField(blank=True, help_text='Наприклад: "Знайди свій PRO-Vision"', max_length=100, verbose_name='Текст бейджа')),
                ('badge_color', models.CharField(choices=[('#3B82F6', 'Блакитний'), ('#F97316', 'Помаранчевий'), ('#E11D48', 'Червоний'), ('#EC4899', 'Рожевий'), ('#8B5CF6', 'Фіолетовий'), ('#10B981', 'Зелений'), ('#F59E0B', 'Жовтий'), ('#6B7280', 'Сірий')], default='#3B82F6', max_length=7, verbose_name='Колір бейджа')),
                ('feature_1', models.CharField(help_text="Обов'язкова", max_length=200, verbose_name='Перевага 1')),
                ('feature_2', models.CharField(blank=True, max_length=200, verbose_name='Перевага 2')),
                ('feature_3', models.CharField(blank=True, max_length=200, verbose_name='Перевага 3')),
                ('feature_4', models.CharField(blank=True, max_length=200, verbose_name='Перевага 4')),
                ('feature_5', models.CharField(blank=True, max_length=200, verbose_name='Перевага 5')),
                ('base_price_uah', models.DecimalField(decimal_places=2, help_text='Ціна за 1 місяць в гривнях', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Базова ціна (грн/міс)')),
                ('base_price_usd', models.DecimalField(decimal_places=2, help_text='Ціна за 1 місяць в доларах', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Базова ціна ($/міс)')),
                ('discount_3_months', models.IntegerField(default=0, help_text='Відсоток знижки для 3-місячної підписки', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка на 3 місяці (%)')),
                ('discount_12_months', models.IntegerField(default=0, help_text='Відсоток знижки для річної підписки', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка на рік (%)')),
                ('available_monthly', models.BooleanField(default=True, verbose_name='Доступно на місяць')),
                ('available_3_months', models.BooleanField(default=True, verbose_name='Доступно на 3 місяці')),
                ('available_12_months', models.BooleanField(default=True, verbose_name='Доступно на рік')),
                ('unavailable_text', models.CharField(default='Доступно в тарифі від 3 місяців', help_text='Показується замість кнопки, коли період недоступний', max_length=100, verbose_name='Текст для недоступних періодів')),
                ('checkout_url', models.URLField(blank=True, help_text='Посилання на зовнішній сервіс квітка', verbose_name='URL сторінки оплати')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Чим менше число, тим раніше відображається', verbose_name='Порядок відображення')),
                ('is_active', models.BooleanField(default=True, help_text='Показувати на сайті', verbose_name='Активний')),
                ('is_popular', models.BooleanField(default=False, help_text='Виділити як найпопулярніший тариф', verbose_name='Популярний')),
                ('meta_title', models.CharField(blank=True, help_text='Для SEO (залиште порожнім для автогенерації)', max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Для SEO', max_length=300, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Тарифний план',
                'verbose_name_plural': 'Тарифні плани',
                'db_table': 'subscription_plans',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Підписка користувача',
                'verbose_name_plural': 'Підписки користувачів',
                'db_table': 'user_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]

