# Generated by Django 5.1.6 on 2025-10-26 10:57

import django.db.models.deletion
from django.db import migrations, models, connection


def add_payment_fields_if_not_exist(apps, schema_editor):
    """Додає поля до payments тільки якщо вони не існують"""
    db_alias = schema_editor.connection.alias
    
    with connection.cursor() as cursor:
        # Перевіряємо які колонки існують
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='payments' AND table_schema='public'
            """)
            existing_columns = {row[0] for row in cursor.fetchall()}
        else:
            # SQLite
            cursor.execute("PRAGMA table_info(payments)")
            existing_columns = {row[1] for row in cursor.fetchall()}
        
        # Додаємо поля, яких немає
        fields_to_add = {
            'subscription_id': "ALTER TABLE payments ADD COLUMN subscription_id BIGINT REFERENCES subscriptions(id)",
            'course_id': "ALTER TABLE payments ADD COLUMN course_id BIGINT REFERENCES courses(id)",
            'event_ticket_id': "ALTER TABLE payments ADD COLUMN event_ticket_id BIGINT REFERENCES event_tickets(id)"
        }
        
        for field_name, sql in fields_to_add.items():
            if field_name not in existing_columns:
                try:
                    cursor.execute(sql)
                    print(f"Added column {field_name} to payments table")
                except Exception as e:
                    print(f"Warning: Could not add {field_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rename_monthly_quotes_month_active_idx_monthly_quo_month_cc6c8a_idx_and_more'),
        ('events', '0006_eventfeedback_eventwaitlist_and_more'),
        ('payments', '0001_initial'),
        ('subscriptions', '0002_plan_improvements'),
    ]

    operations = [
        # Спершу виконуємо RunPython для додавання полів
        migrations.RunPython(add_payment_fields_if_not_exist, migrations.RunPython.noop),
    ]
