# Generated by Django 5.1.6 on 2025-10-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rename_monthly_quotes_month_active_idx_monthly_quo_month_cc6c8a_idx_and_more'),
        ('events', '0006_eventfeedback_eventwaitlist_and_more'),
        ('payments', '0001_initial'),
        ('subscriptions', '0002_plan_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='content.course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='event_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='events.eventticket'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription'),
        ),
    ]
