# Generated by Django 5.1.6 on 2025-11-17 01:00
# Empty migration - stub to satisfy migration history

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_course_payment_event_ticket_and_more'),
    ]

    operations = [
        # Empty - поля вже додані в 0002
    ]

