# Generated by Django 5.1.3 on 2025-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiknowledgedocument',
            name='file',
            field=models.FileField(max_length=500, upload_to='ai/knowledge/', verbose_name='Файл'),
        ),
    ]

