# Generated by Django 5.1.6 on 2025-09-06 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(help_text='Кроки воронки з умовами')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversion Funnel',
                'verbose_name_plural': 'Conversion Funnels',
                'db_table': 'analytics_funnels',
            },
        ),
        migrations.CreateModel(
            name='RevenueAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue_type', models.CharField(choices=[('subscription', 'Підписка'), ('course', 'Курс'), ('event', 'Івент'), ('mentoring', 'Ментор-коучінг')], max_length=20)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transactions', models.PositiveIntegerField(default=0)),
                ('unique_customers', models.PositiveIntegerField(default=0)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Revenue Analytics',
                'verbose_name_plural': 'Revenue Analytics',
                'db_table': 'analytics_revenue',
                'unique_together': {('date', 'revenue_type')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session ID для анонімних користувачів', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('referrer', models.URLField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'analytics_sessions',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('time_on_page_seconds', models.PositiveIntegerField(default=0)),
                ('max_scroll_percentage', models.PositiveIntegerField(default=0)),
                ('had_interaction', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.usersession')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'db_table': 'analytics_page_views',
            },
        ),
        migrations.CreateModel(
            name='FunnelStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='analytics.conversionfunnel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_steps', to='analytics.usersession')),
            ],
            options={
                'verbose_name': 'Funnel Step',
                'verbose_name_plural': 'Funnel Steps',
                'db_table': 'analytics_funnel_steps',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('engagement', 'Взаємодія'), ('conversion', 'Конверсія'), ('content', 'Контент'), ('commerce', 'Комерція'), ('social', 'Соціальна активність')], max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('value', models.FloatField(blank=True, null=True)),
                ('page_path', models.CharField(blank=True, max_length=500)),
                ('properties', models.JSONField(default=dict, help_text='Додаткові властивості події')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.usersession')),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'db_table': 'analytics_events',
            },
        ),
        migrations.CreateModel(
            name='ContentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('avg_time_spent', models.PositiveIntegerField(default=0, help_text='Середній час у секундах')),
                ('completion_rate', models.FloatField(default=0, help_text='Відсоток завершення')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('bookmarks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Analytics',
                'verbose_name_plural': 'Content Analytics',
                'db_table': 'analytics_content',
                'indexes': [models.Index(fields=['date', 'view_count'], name='analytics_c_date_2c3e92_idx')],
                'unique_together': {('content_type', 'object_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('total_time_minutes', models.PositiveIntegerField(default=0)),
                ('pages_viewed', models.PositiveIntegerField(default=0)),
                ('courses_viewed', models.PositiveIntegerField(default=0)),
                ('courses_started', models.PositiveIntegerField(default=0)),
                ('courses_completed', models.PositiveIntegerField(default=0)),
                ('events_attended', models.PositiveIntegerField(default=0)),
                ('mentoring_sessions', models.PositiveIntegerField(default=0)),
                ('purchases_made', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Behavior Metrics',
                'verbose_name_plural': 'User Behavior Metrics',
                'db_table': 'analytics_user_behavior',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'started_at'], name='analytics_s_user_id_89d06e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_id'], name='analytics_s_session_a33eff_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session', 'viewed_at'], name='analytics_p_session_a37bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['path'], name='analytics_p_path_76024a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='funnelstep',
            unique_together={('funnel', 'session', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['session', 'timestamp'], name='analytics_e_session_b71835_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_name', 'category'], name='analytics_e_event_n_b18975_idx'),
        ),
    ]
