# Generated by Django 5.1.6 on 2025-11-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date for this stats snapshot', unique=True)),
                ('total_users', models.PositiveIntegerField(default=0, help_text='Total registered users')),
                ('new_users_today', models.PositiveIntegerField(default=0, help_text='New users registered today')),
                ('active_users_today', models.PositiveIntegerField(default=0, help_text='Unique users active today')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue all time', max_digits=12)),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0, help_text='Revenue generated today', max_digits=10)),
                ('avg_session_duration', models.PositiveIntegerField(default=0, help_text='Average session duration today (seconds)')),
                ('total_time_on_site', models.PositiveIntegerField(default=0, help_text='Total time users spent today (seconds)')),
                ('course_views_json', models.JSONField(default=dict, help_text='Top course views: {course_id: count}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Stats',
                'verbose_name_plural': 'Dashboard Stats',
                'db_table': 'analytics_dashboard_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='analytics_d_date_6c9420_idx'), models.Index(fields=['-updated_at'], name='analytics_d_updated_18a87c_idx')],
            },
        ),
    ]
