# Generated by Django 5.1.6 on 2025-09-06 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('banner_type', models.CharField(choices=[('hero', 'Hero банер'), ('promotion', 'Промо'), ('announcement', 'Оголошення'), ('subscription', 'Підписка'), ('event', 'Івент')], max_length=20)),
                ('position', models.CharField(choices=[('header', 'Хедер'), ('hero', 'Hero секція'), ('sidebar', 'Бокова панель'), ('footer', 'Футер'), ('popup', 'Спливаюче вікно')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='cms/banners/')),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_url', models.CharField(blank=True, max_length=200)),
                ('cta_button_color', models.CharField(default='#ff6b35', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('show_from', models.DateTimeField(blank=True, null=True)),
                ('show_until', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Більше число = вища пріоритетність')),
                ('show_to_guests', models.BooleanField(default=True)),
                ('show_to_users', models.BooleanField(default=True)),
                ('show_to_subscribers', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'cms_banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block_type', models.CharField(choices=[('text', 'Текстовий блок'), ('image', 'Зображення'), ('video', 'Відео'), ('carousel', 'Карусель'), ('cta', 'Заклик до дії'), ('testimonials', 'Відгуки'), ('faq', 'FAQ'), ('stats', 'Статистика')], max_length=20)),
                ('content', models.JSONField(help_text='Контент блоку у форматі JSON')),
                ('css_classes', models.CharField(blank=True, max_length=200)),
                ('custom_css', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'db_table': 'cms_content_blocks',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'Загальні'), ('subscription', 'Підписка'), ('courses', 'Курси'), ('events', 'Івенти'), ('payments', 'Оплата'), ('technical', 'Технічні')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('not_helpful_votes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'cms_faq',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('setting_type', models.CharField(choices=[('string', 'Рядок'), ('text', 'Текст'), ('boolean', 'Булевий'), ('integer', 'Число'), ('float', 'Десяткове'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(help_text='Опис призначення налаштування')),
                ('group', models.CharField(default='general', help_text='Група налаштувань (general, email, payment тощо)', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='Доступно через API')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'db_table': 'cms_settings',
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Рейтинг від 1 до 5')),
                ('photo', models.ImageField(blank=True, upload_to='cms/testimonials/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'cms_testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('main', 'Головне меню'), ('footer', 'Меню футера'), ('mobile', 'Мобільне меню'), ('user', 'Меню користувача')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Відносний або абсолютний URL', max_length=200)),
                ('icon', models.CharField(blank=True, help_text='CSS клас іконки', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('require_auth', models.BooleanField(default=False)),
                ('require_subscription', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'cms_menu_items',
                'ordering': ['menu_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Короткий опис для превью')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано'), ('archived', 'Архівовано')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CMS Page',
                'verbose_name_plural': 'CMS Pages',
                'db_table': 'cms_pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
