# Generated by Django 5.1.6 on 2025-11-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_add_cms_models'),
        ('content', '0013_rename_monthly_quotes_month_active_idx_monthly_quo_month_cc6c8a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGridCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Позиція в сітці (1-9): 1=верх зліва, 9=низ справа', unique=True, verbose_name='Позиція')),
                ('image', models.ImageField(help_text='Зображення або GIF для комірки', upload_to='cms/event_grid/', verbose_name='Зображення/GIF')),
                ('alt_text', models.CharField(blank=True, help_text='Опис зображення для доступності', max_length=200, verbose_name='Alt текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Комірка сітки івентів',
                'verbose_name_plural': 'Комірки сітки івентів',
                'db_table': 'cms_event_grid_cells',
                'ordering': ['position'],
                'constraints': [models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 9)), name='event_grid_cell_position_range')],
            },
        ),
        migrations.CreateModel(
            name='PageSVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Унікальна назва SVG (наприклад: about_section2)', max_length=100, unique=True, verbose_name='Назва')),
                ('page', models.CharField(db_index=True, help_text='Сторінка де використовується (about, mentor, home)', max_length=50, verbose_name='Сторінка')),
                ('section', models.CharField(blank=True, help_text='Номер секції (section2, section3 тощо)', max_length=50, verbose_name='Секція')),
                ('svg_ua_light', models.TextField(help_text='SVG код для України в світлій темі', verbose_name='SVG (Ukraine, Light)')),
                ('svg_ua_dark', models.TextField(blank=True, help_text='SVG код для України в темній темі', verbose_name='SVG (Ukraine, Dark)')),
                ('svg_world_light', models.TextField(blank=True, help_text='SVG код для світу в світлій темі (якщо порожнє - показується UA)', verbose_name='SVG (World, Light)')),
                ('svg_world_dark', models.TextField(blank=True, help_text='SVG код для світу в темній темі', verbose_name='SVG (World, Dark)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SVG елемент',
                'verbose_name_plural': 'SVG елементи',
                'db_table': 'cms_page_svg',
                'ordering': ['page', 'section', 'name'],
                'indexes': [models.Index(fields=['page', 'is_active'], name='cms_page_sv_page_30b133_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackingPixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Описова назва пікселя', max_length=100, verbose_name='Назва')),
                ('pixel_type', models.CharField(choices=[('facebook', 'Facebook Pixel'), ('google_analytics', 'Google Analytics'), ('google_tag_manager', 'Google Tag Manager'), ('custom', 'Custom Pixel')], max_length=30, verbose_name='Тип пікселя')),
                ('pixel_id', models.CharField(help_text='FB Pixel ID, GA Measurement ID тощо', max_length=100, verbose_name='ID пікселя')),
                ('code_snippet', models.TextField(help_text='Повний код для вставки в template', verbose_name='Код пікселя')),
                ('placement', models.CharField(choices=[('head', 'Head Section'), ('body_start', 'Body Start'), ('body_end', 'Body End')], default='head', help_text='Де розмістити код', max_length=20, verbose_name='Розташування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracking Pixel',
                'verbose_name_plural': 'Tracking Pixels',
                'db_table': 'cms_tracking_pixels',
                'ordering': ['-created_at'],
                'unique_together': {('pixel_type', 'pixel_id')},
            },
        ),
        migrations.CreateModel(
            name='FeaturedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, default='home', help_text='На якій сторінці відображати (home, hub тощо)', max_length=50, verbose_name='Сторінка')),
                ('order', models.PositiveIntegerField(help_text='Порядок відображення (1-12)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Курс для відображення на головній', on_delete=django.db.models.deletion.CASCADE, to='content.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Вибраний курс',
                'verbose_name_plural': 'Вибрані курси',
                'db_table': 'cms_featured_courses',
                'ordering': ['page', 'order'],
                'indexes': [models.Index(fields=['page', 'is_active', 'order'], name='cms_feature_page_0fe6cc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('order__gte', 1), ('order__lte', 12)), name='featured_course_order_range')],
                'unique_together': {('page', 'course'), ('page', 'order')},
            },
        ),
    ]
