# Generated by Django 5.1.6 on 2025-11-17 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_heroslide_dual_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=200, verbose_name='Заголовок (Україна)')),
                ('subtitle_ua', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (Україна)')),
                ('image_ua', models.ImageField(blank=True, upload_to='cms/about/hero/', verbose_name='Зображення (Україна)')),
                ('title_world', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (Світ)')),
                ('subtitle_world', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (Світ)')),
                ('image_world', models.ImageField(blank=True, upload_to='cms/about/hero/', verbose_name='Зображення (Світ)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero секція',
                'verbose_name_plural': 'Hero секція (Про нас)',
                'db_table': 'cms_about_hero',
            },
        ),
        migrations.CreateModel(
            name='AboutSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ua_light', models.ImageField(upload_to='cms/about/section2/', verbose_name='Картинка UA (світла тема)')),
                ('image_ua_dark', models.ImageField(upload_to='cms/about/section2/', verbose_name='Картинка UA (темна тема)')),
                ('image_world_light', models.ImageField(blank=True, upload_to='cms/about/section2/', verbose_name='Картинка World (світла)')),
                ('image_world_dark', models.ImageField(blank=True, upload_to='cms/about/section2/', verbose_name='Картинка World (темна)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Секція 2',
                'verbose_name_plural': 'Секція 2 (Про нас)',
                'db_table': 'cms_about_section2',
            },
        ),
        migrations.CreateModel(
            name='AboutSection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=200, verbose_name='Заголовок (Україна)')),
                ('title_world', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (Світ)')),
                ('svg_ua_light', models.TextField(verbose_name='SVG UA (світла)')),
                ('svg_ua_dark', models.TextField(blank=True, verbose_name='SVG UA (темна)')),
                ('svg_world_light', models.TextField(blank=True, verbose_name='SVG World (світла)')),
                ('svg_world_dark', models.TextField(blank=True, verbose_name='SVG World (темна)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Секція 3',
                'verbose_name_plural': 'Секція 3 (Про нас)',
                'db_table': 'cms_about_section3',
            },
        ),
        migrations.CreateModel(
            name='AboutSection4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=200, verbose_name='Заголовок (Україна)')),
                ('title_world', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (Світ)')),
                ('svg_ua_light', models.TextField(verbose_name='SVG UA (світла)')),
                ('svg_ua_dark', models.TextField(blank=True, verbose_name='SVG UA (темна)')),
                ('svg_world_light', models.TextField(blank=True, verbose_name='SVG World (світла)')),
                ('svg_world_dark', models.TextField(blank=True, verbose_name='SVG World (темна)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Секція 4',
                'verbose_name_plural': 'Секція 4 (Про нас)',
                'db_table': 'cms_about_section4',
            },
        ),
        migrations.CreateModel(
            name='HubHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='cms/hub/hero/', verbose_name='Фонове зображення')),
                ('title_1_ua', models.CharField(max_length=200, verbose_name='Заголовок 1 (Україна)')),
                ('subtitle_1_ua', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок 1 (Україна)')),
                ('title_1_world', models.CharField(blank=True, max_length=200, verbose_name='Заголовок 1 (Світ)')),
                ('subtitle_1_world', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок 1 (Світ)')),
                ('title_2_ua', models.CharField(blank=True, max_length=200, verbose_name='Заголовок 2 (Україна)')),
                ('subtitle_2_ua', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок 2 (Україна)')),
                ('title_2_world', models.CharField(blank=True, max_length=200, verbose_name='Заголовок 2 (Світ)')),
                ('subtitle_2_world', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок 2 (Світ)')),
                ('title_3_ua', models.CharField(blank=True, max_length=200, verbose_name='Заголовок 3 (Україна)')),
                ('subtitle_3_ua', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок 3 (Україна)')),
                ('title_3_world', models.CharField(blank=True, max_length=200, verbose_name='Заголовок 3 (Світ)')),
                ('subtitle_3_world', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок 3 (Світ)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero секція',
                'verbose_name_plural': 'Hero секція (Хаб знань)',
                'db_table': 'cms_hub_hero',
            },
        ),
        migrations.CreateModel(
            name='MentorHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cms/mentor/hero/', verbose_name='Зображення Hero')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero блок',
                'verbose_name_plural': 'Hero блок (Ментор коучинг)',
                'db_table': 'cms_mentor_hero',
            },
        ),
        migrations.CreateModel(
            name='MentorSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=200, verbose_name='Заголовок (Україна)')),
                ('title_world', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (Світ)')),
                ('svg_ua_light', models.TextField(verbose_name='SVG UA (світла)')),
                ('svg_ua_dark', models.TextField(blank=True, verbose_name='SVG UA (темна)')),
                ('svg_world_light', models.TextField(blank=True, verbose_name='SVG World (світла)')),
                ('svg_world_dark', models.TextField(blank=True, verbose_name='SVG World (темна)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Секція 2',
                'verbose_name_plural': 'Секція 2 (Ментор коучинг)',
                'db_table': 'cms_mentor_section2',
            },
        ),
        migrations.CreateModel(
            name='MentorSection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_ua_light', models.TextField(verbose_name='SVG UA (світла)')),
                ('svg_ua_dark', models.TextField(blank=True, verbose_name='SVG UA (темна)')),
                ('svg_world_light', models.TextField(blank=True, verbose_name='SVG World (світла)')),
                ('svg_world_dark', models.TextField(blank=True, verbose_name='SVG World (темна)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Секція 3',
                'verbose_name_plural': 'Секція 3 (Ментор коучинг)',
                'db_table': 'cms_mentor_section3',
            },
        ),
        migrations.CreateModel(
            name='MentorSection4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=200, verbose_name='Заголовок (Україна)')),
                ('subtitle_ua', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (Україна)')),
                ('title_world', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (Світ)')),
                ('subtitle_world', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (Світ)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Секція 4',
                'verbose_name_plural': 'Секція 4 (Ментор коучинг)',
                'db_table': 'cms_mentor_section4',
            },
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='badge',
            field=models.CharField(blank=True, help_text='Badge text (e.g. "NEW", "TRENDING")', max_length=50, verbose_name='Badge'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_text_ua',
            field=models.CharField(blank=True, max_length=50, verbose_name='CTA Text (Ukraine)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='CTA URL'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 1920×1080 px', upload_to='cms/hero/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position in carousel (1-7)', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_ua',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtitle (Ukraine)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title_ua',
            field=models.CharField(max_length=200, verbose_name='Title (Ukraine)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title_world',
            field=models.CharField(blank=True, help_text='Leave blank to use Ukraine version worldwide', max_length=200, verbose_name='Title (World)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 format', upload_to='cms/hero/videos/', verbose_name='Video'),
        ),
        migrations.CreateModel(
            name='MentorSection1Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Позиція')),
                ('image_ua', models.ImageField(upload_to='cms/mentor/section1/', verbose_name='Картинка (Україна)')),
                ('caption_ua', models.CharField(max_length=200, verbose_name='Підпис (Україна)')),
                ('image_world', models.ImageField(blank=True, upload_to='cms/mentor/section1/', verbose_name='Картинка (Світ)')),
                ('caption_world', models.CharField(blank=True, max_length=200, verbose_name='Підпис (Світ)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Секція 1 - 3 картинки (Ментор коучинг)',
                'db_table': 'cms_mentor_section1_images',
                'ordering': ['position'],
                'constraints': [models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 3)), name='mentor_section1_position_range')],
            },
        ),
    ]
