# Generated by Django 5.1.6 on 2025-11-17 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_abouthero_aboutsection2_aboutsection3_aboutsection4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorCoachingSVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_ua_light', models.TextField(verbose_name='SVG UA (світла тема)')),
                ('svg_ua_dark', models.TextField(blank=True, verbose_name='SVG UA (темна тема)')),
                ('svg_world_light', models.TextField(blank=True, verbose_name='SVG World (світла)')),
                ('svg_world_dark', models.TextField(blank=True, verbose_name='SVG World (темна)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ментор коучинг SVG',
                'verbose_name_plural': 'Ментор коучинг (Головна сторінка)',
                'db_table': 'cms_mentor_coaching_svg',
            },
        ),
        migrations.AlterModelOptions(
            name='mentorsection4',
            options={'verbose_name': 'Секція 4', 'verbose_name_plural': 'Секція 4 + Команда (Ментор коучинг)'},
        ),
        migrations.RemoveConstraint(
            model_name='mentorsection1image',
            name='mentor_section1_position_range',
        ),
        migrations.AddField(
            model_name='abouthero',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='aboutsection2',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='aboutsection3',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='aboutsection4',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='hubhero',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='mentorhero',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='mentorsection1image',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='mentorsection2',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='mentorsection3',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='mentorsection4',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='title_world',
            field=models.CharField(blank=True, help_text='Залиште порожнім щоб показувати українську версію', max_length=200, verbose_name='Заголовок (Світ)'),
        ),
        migrations.AlterField(
            model_name='aboutsection2',
            name='image_ua_dark',
            field=models.ImageField(blank=True, upload_to='cms/about/section2/', verbose_name='Картинка UA (темна тема)'),
        ),
        migrations.AlterField(
            model_name='aboutsection3',
            name='svg_ua_dark',
            field=models.TextField(blank=True, verbose_name='SVG UA (темна тема)'),
        ),
        migrations.AlterField(
            model_name='aboutsection3',
            name='svg_ua_light',
            field=models.TextField(verbose_name='SVG UA (світла тема)'),
        ),
        migrations.AlterField(
            model_name='aboutsection4',
            name='svg_ua_dark',
            field=models.TextField(blank=True, verbose_name='SVG UA (темна тема)'),
        ),
        migrations.AlterField(
            model_name='aboutsection4',
            name='svg_ua_light',
            field=models.TextField(verbose_name='SVG UA (світла тема)'),
        ),
        migrations.AlterField(
            model_name='mentorhero',
            name='image',
            field=models.ImageField(upload_to='cms/mentor/hero/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='mentorsection1image',
            name='position',
            field=models.PositiveIntegerField(help_text='Позиція картинки (1, 2 або 3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='mentorsection2',
            name='svg_ua_dark',
            field=models.TextField(blank=True, verbose_name='SVG UA (темна тема)'),
        ),
        migrations.AlterField(
            model_name='mentorsection2',
            name='svg_ua_light',
            field=models.TextField(verbose_name='SVG UA (світла тема)'),
        ),
        migrations.AlterField(
            model_name='mentorsection3',
            name='svg_ua_dark',
            field=models.TextField(blank=True, verbose_name='SVG UA (темна тема)'),
        ),
        migrations.AlterField(
            model_name='mentorsection3',
            name='svg_ua_light',
            field=models.TextField(verbose_name='SVG UA (світла тема)'),
        ),
    ]
