# Generated by Django 5.1.6 on 2025-11-17 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        # Dummy - все вже застосовано на Render
    ]
