# Generated by Django 5.1.6 on 2025-11-20 14:00
# Migration to sync Django state with existing database tables

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_new_page_models'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Add HeroSlide model to Django state
                migrations.CreateModel(
                    name='HeroSlide',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title_ua', models.CharField(max_length=200, verbose_name='Title (Ukraine)')),
                        ('subtitle_ua', models.CharField(blank=True, max_length=300, verbose_name='Subtitle (Ukraine)')),
                        ('cta_text_ua', models.CharField(blank=True, max_length=50, verbose_name='CTA Text (Ukraine)')),
                        ('title_world', models.CharField(blank=True, help_text='Leave blank to use Ukraine version worldwide', max_length=200, verbose_name='Title (World)')),
                        ('subtitle_world', models.CharField(blank=True, max_length=300, verbose_name='Subtitle (World)')),
                        ('cta_text_world', models.CharField(blank=True, max_length=50, verbose_name='CTA Text (World)')),
                        ('badge', models.CharField(blank=True, help_text='Badge text (e.g. "NEW", "TRENDING")', max_length=50, verbose_name='Badge')),
                        ('image', models.ImageField(blank=True, help_text='Recommended: 1920×1080 px', max_length=100, upload_to='cms/hero/', verbose_name='Image')),
                        ('video', models.FileField(blank=True, help_text='MP4 format', max_length=100, upload_to='cms/hero/videos/', verbose_name='Video')),
                        ('cta_url', models.CharField(blank=True, max_length=200, verbose_name='CTA URL')),
                        ('order', models.PositiveIntegerField(default=0, help_text='Position in carousel (1-7)', verbose_name='Order')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Hero Слайд',
                        'verbose_name_plural': '🏠 Головна → Hero блок',
                        'db_table': 'cms_hero_slides',
                        'ordering': ['order', '-created_at'],
                    },
                ),
                # Add ExpertCard model to Django state
                migrations.CreateModel(
                    name='ExpertCard',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                        ('position', models.CharField(max_length=150, verbose_name='Посада')),
                        ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Спеціалізація')),
                        ('bio', models.TextField(blank=True, verbose_name='Біографія')),
                        ('photo', models.ImageField(blank=True, help_text='Рекомендований розмір: 400×400 px', max_length=100, upload_to='cms/experts/', verbose_name='Фото')),
                        ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                        ('show_on_homepage', models.BooleanField(default=True, verbose_name='Показувати на головній')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Спеціаліст',
                        'verbose_name_plural': 'Команда (використовується скрізь)',
                        'db_table': 'cms_expert_cards',
                        'ordering': ['order'],
                    },
                ),
                # Add FeaturedCourse model to Django state
                migrations.CreateModel(
                    name='FeaturedCourse',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('page', models.CharField(db_index=True, default='home', help_text='На якій сторінці відображати (home, hub тощо)', max_length=50, verbose_name='Сторінка')),
                        ('order', models.PositiveIntegerField(help_text='Порядок відображення (1-12)', verbose_name='Порядок')),
                        ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активний')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('course', models.ForeignKey(help_text='Курс для відображення на головній', on_delete=django.db.models.deletion.CASCADE, to='content.course', verbose_name='Курс')),
                    ],
                    options={
                        'verbose_name': 'Курс',
                        'verbose_name_plural': '🏠 Головна → Основні програми',
                        'db_table': 'cms_featured_courses',
                        'ordering': ['page', 'order'],
                        'indexes': [models.Index(fields=['page', 'is_active', 'order'], name='cms_feature_page_cc6c8a_idx')],
                    },
                ),
                migrations.AddConstraint(
                    model_name='featuredcourse',
                    constraint=models.CheckConstraint(check=models.Q(('order__gte', 1), ('order__lte', 12)), name='featured_course_order_range'),
                ),
                migrations.AlterUniqueTogether(
                    name='featuredcourse',
                    unique_together={('page', 'order'), ('page', 'course')},
                ),
                # Add EventGridCell model to Django state
                migrations.CreateModel(
                    name='EventGridCell',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('position', models.PositiveIntegerField(help_text='Позиція в сітці (1-9): 1=верх зліва, 9=низ справа', unique=True, verbose_name='Позиція')),
                        ('image', models.ImageField(help_text='Зображення або GIF для комірки', max_length=100, upload_to='cms/event_grid/', verbose_name='Зображення/GIF')),
                        ('alt_text', models.CharField(blank=True, help_text='Опис зображення для доступності', max_length=200, verbose_name='Alt текст')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Комірка сітки',
                        'verbose_name_plural': '🎉 Івенти → Hero сітка',
                        'db_table': 'cms_event_grid_cells',
                        'ordering': ['position'],
                    },
                ),
                migrations.AddConstraint(
                    model_name='eventgridcell',
                    constraint=models.CheckConstraint(check=models.Q(('position__gte', 1), ('position__lte', 9)), name='event_grid_cell_position_range'),
                ),
            ],
            # No database operations - tables already exist
            database_operations=[],
        ),
    ]

