# Generated by Django 5.1.6 on 2025-11-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_new_page_models'),
    ]

    operations = [
        # Спочатку СТВОРЮЄМО модель EventGridCell
        migrations.CreateModel(
            name='EventGridCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Позиція в сітці (1-9): 1=верх зліва, 9=низ справа', unique=True, verbose_name='Позиція')),
                ('image', models.ImageField(help_text='Зображення або GIF для комірки', max_length=500, upload_to='cms/event_grid/', verbose_name='Зображення/GIF')),
                ('alt_text', models.CharField(blank=True, help_text='Опис зображення для доступності', max_length=200, verbose_name='Alt текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Комірка сітки',
                'verbose_name_plural': '🎉 Івенти → Hero сітка',
                'db_table': 'cms_event_grid_cells',
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventgridcell',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 1), ('position__lte', 9)), name='event_grid_cell_position_range'),
        ),
        # ПОТІМ змінюємо інші моделі
        migrations.AlterField(
            model_name='expertcard',
            name='photo',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір: 400×400 px', max_length=500, upload_to='cms/experts/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 1920×1080 px', max_length=500, upload_to='cms/hero/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 format', max_length=500, upload_to='cms/hero/videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='image_ua',
            field=models.ImageField(blank=True, max_length=500, upload_to='cms/about/hero/', verbose_name='Зображення (Україна)'),
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='image_world',
            field=models.ImageField(blank=True, max_length=500, upload_to='cms/about/hero/', verbose_name='Зображення (Світ)'),
        ),
        migrations.AlterField(
            model_name='aboutsection2',
            name='image_ua_dark',
            field=models.ImageField(blank=True, max_length=500, upload_to='cms/about/section2/', verbose_name='Картинка UA (темна тема)'),
        ),
        migrations.AlterField(
            model_name='aboutsection2',
            name='image_ua_light',
            field=models.ImageField(max_length=500, upload_to='cms/about/section2/', verbose_name='Картинка UA (світла тема)'),
        ),
        migrations.AlterField(
            model_name='aboutsection2',
            name='image_world_dark',
            field=models.ImageField(blank=True, max_length=500, upload_to='cms/about/section2/', verbose_name='Картинка World (темна)'),
        ),
        migrations.AlterField(
            model_name='aboutsection2',
            name='image_world_light',
            field=models.ImageField(blank=True, max_length=500, upload_to='cms/about/section2/', verbose_name='Картинка World (світла)'),
        ),
        migrations.AlterField(
            model_name='hubhero',
            name='background_image',
            field=models.ImageField(max_length=500, upload_to='cms/hub/hero/', verbose_name='Фонове зображення'),
        ),
        migrations.AlterField(
            model_name='mentorhero',
            name='image',
            field=models.ImageField(max_length=500, upload_to='cms/mentor/hero/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='mentorsection1image',
            name='image_ua',
            field=models.ImageField(max_length=500, upload_to='cms/mentor/section1/', verbose_name='Картинка (Україна)'),
        ),
        migrations.AlterField(
            model_name='mentorsection1image',
            name='image_world',
            field=models.ImageField(blank=True, max_length=500, upload_to='cms/mentor/section1/', verbose_name='Картинка (Світ)'),
        ),
    ]
